version: "3.7"
services:
  frontend:
    image: catalingavan/logbee.frontend:1.2.1.3
    init: true
    restart: unless-stopped
    volumes:
      - configuration:/app/configuration
    ports:
      - "44080:80"
